server:
  port: 8085

spring:
  application:
    name: medical-record-service

  data:
    mongodb:
      host: hospital-mongo
      port: 27017
      database: medical_record_db
      username: mongo
      password: mongopass123
      authentication-database: admin
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
