server:
  port: 8085

spring:
  application:
    name: medical-record-service

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/medical_record_db}

  data:
    mongodb:
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: false
